const strings = {
  English: {
    // Splash
    tagline: 'Your daily mental wellness companion',
    // Onboarding
    welcome_heading: "Hey! I'm Bridge. 👋",
    welcome_body: "I'm here to listen — no judgment, no pressure. Just a safe space for you to be honest about how you're feeling.",
    welcome_cta: "Let's get started",
    name_heading: "What should I call you?",
    name_placeholder: "Your first name",
    age_heading: "How old are you?",
    age_groups: ['14–17', '18–22', '23–28'],
    lang_heading: "Which language feels most comfortable?",
    feeling_heading: "What's been weighing on you?",
    feeling_subheading: "You can share anything — or skip for now.",
    feeling_placeholder: "I've been feeling...",
    skip: "Skip for now",
    continue: "Continue",
    finish: "Start my journey →",
    // Home
    home_greeting_morning: "Good morning",
    home_greeting_afternoon: "Good afternoon",
    home_greeting_evening: "Good evening",
    home_greeting_night: "Hey",
    check_in_title: "How are you feeling today?",
    check_in_cta: "Start today's check-in",
    checked_in: "You've checked in today ✓",
    talk_to_bridge: "Talk to Bridge",
    mood_dashboard: "Mood Dashboard",
    get_help: "Get Help",
    privacy_note: "🔒 Your conversations stay on your device. Always.",
    streak: "day streak",
    // Check-in
    how_feeling: "How are you feeling right now?",
    whats_going_on: "What's going on? (optional)",
    note_placeholder: "Share anything on your mind...",
    getting_response: "Bridge is thinking...",
    done: "Done",
    // Mood labels
    mood_great: "Great",
    mood_good: "Good",
    mood_okay: "Okay",
    mood_low: "Low",
    mood_struggling: "Really\nStruggling",
    // Mood Dashboard
    dashboard_title: "Your Mood Journey",
    week_view: "This Week",
    month_view: "30 Days",
    your_week: "Your week in words",
    generating: "Bridge is reflecting...",
    streak_label: "Check-in streak",
    no_data: "No data yet — complete your first check-in!",
    // Resources
    resources_title: "Get Support",
    resources_subtitle: "Real humans ready to listen. All resources are free.",
    call: "Call now",
    chat: "Chat online",
    filter_all: "All",
    filter_free: "Free",
    filter_24x7: "24×7",
    filter_hindi: "Hindi",
    // Crisis modal
    crisis_heading: "You're not alone.",
    crisis_body: "Let's make sure you get the support you deserve right now.",
    crisis_btn1: "Call iCall — 9152987821",
    crisis_btn2: "Call Vandrevala — 1860-2662-345",
    crisis_btn3: "Dial Tele MANAS — 14416",
    crisis_back: "I'm okay, take me back",
    // Chat
    chat_placeholder: "Type something...",
    chat_offer: "Would you like to talk to a trained counselor?",
    chat_offer_cta: "Find a counselor →",
    // Nav
    home: "Home",
    chat: "Chat",
    dashboard: "Progress",
    resources: "Help",
  },
  Hindi: {
    tagline: 'आपका दैनिक मानसिक स्वास्थ्य साथी',
    welcome_heading: 'नमस्ते! मैं Bridge हूँ। 👋',
    welcome_body: 'मैं यहाँ सुनने के लिए हूँ — बिना किसी निर्णय के, बिना किसी दबाव के। बस एक सुरक्षित जगह जहाँ आप ईमानदार हो सकते हैं।',
    welcome_cta: 'शुरू करते हैं',
    name_heading: 'मैं आपको क्या बुलाऊँ?',
    name_placeholder: 'आपका नाम',
    age_heading: 'आपकी उम्र क्या है?',
    age_groups: ['14–17', '18–22', '23–28'],
    lang_heading: 'कौन सी भाषा आपको सबसे सहज लगती है?',
    feeling_heading: 'आपके मन पर क्या चल रहा है?',
    feeling_subheading: 'कुछ भी साझा करें — या अभी के लिए छोड़ दें।',
    feeling_placeholder: 'मुझे ऐसा लग रहा है...',
    skip: 'अभी छोड़ें',
    continue: 'आगे बढ़ें',
    finish: 'शुरू करें →',
    home_greeting_morning: 'सुप्रभात',
    home_greeting_afternoon: 'नमस्ते',
    home_greeting_evening: 'शुभ संध्या',
    home_greeting_night: 'हैलो',
    check_in_title: 'आज आप कैसा महसूस कर रहे हैं?',
    check_in_cta: 'आज का check-in करें',
    checked_in: 'आपने आज check-in किया ✓',
    talk_to_bridge: 'Bridge से बात करें',
    mood_dashboard: 'मूड डैशबोर्ड',
    get_help: 'सहायता लें',
    privacy_note: '🔒 आपकी बातें सिर्फ आपके डिवाइस पर रहती हैं।',
    streak: 'दिन की streak',
    how_feeling: 'अभी आप कैसा महसूस कर रहे हैं?',
    whats_going_on: 'क्या हो रहा है? (वैकल्पिक)',
    note_placeholder: 'अपने मन की बात साझा करें...',
    getting_response: 'Bridge सोच रहा है...',
    done: 'हो गया',
    mood_great: 'बढ़िया',
    mood_good: 'अच्छा',
    mood_okay: 'ठीक है',
    mood_low: 'उदास',
    mood_struggling: 'बहुत\nमुश्किल',
    dashboard_title: 'आपकी मूड यात्रा',
    week_view: 'इस हफ्ते',
    month_view: '30 दिन',
    your_week: 'इस हफ्ते कुछ शब्दों में',
    generating: 'Bridge सोच रहा है...',
    streak_label: 'Check-in streak',
    no_data: 'अभी कोई डेटा नहीं — पहला check-in करें!',
    resources_title: 'सहायता लें',
    resources_subtitle: 'असली इंसान, सुनने के लिए तैयार। सभी मुफ्त।',
    call: 'अभी कॉल करें',
    chat: 'ऑनलाइन चैट',
    filter_all: 'सभी',
    filter_free: 'मुफ्त',
    filter_24x7: '24×7',
    filter_hindi: 'हिंदी',
    crisis_heading: 'आप अकेले नहीं हैं।',
    crisis_body: 'अभी आपको सही सहायता मिलनी चाहिए।',
    crisis_btn1: 'iCall को कॉल करें — 9152987821',
    crisis_btn2: 'Vandrevala — 1860-2662-345',
    crisis_btn3: 'Tele MANAS डायल करें — 14416',
    crisis_back: 'मैं ठीक हूँ, वापस जाएं',
    chat_placeholder: 'कुछ लिखें...',
    chat_offer: 'क्या आप एक trained counselor से बात करना चाहते हैं?',
    chat_offer_cta: 'Counselor खोजें →',
    home: 'होम',
    chat: 'चैट',
    dashboard: 'प्रगति',
    resources: 'सहायता',
  },
};

import { useState, useCallback } from 'react';

export function useLanguage(initial = 'English') {
  const [lang, setLang] = useState(initial);
  const t = useCallback((key) => {
    return strings[lang]?.[key] ?? strings['English']?.[key] ?? key;
  }, [lang]);

  return { lang, setLang, t, strings };
}
